branch-defaults:
  master:
    environment: chatterbox-scheduler-backend-dev
    group_suffix: null
global:
  application_name: chatterbox-scheduler-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
